### ISSUE TITLE
how to run the track.py?  there are no images but videos in mta dataset. However, in track.py, the load_image function is used. ^-^ 

### ISSUE THREAD

**Issue by jellyshuang** [nolanzzz/mtmct#2]

**Comment by nolanzzz** [comment]
I suppose you were referring to `../fair/src/track.py`? It does run on images directly so it requires pre-preparation (dividing videos into image frames with ffmpeg). However, you can easily switch from `LoadImage` to `LoadVideo` and references can be found in `../fair/src/demo.py`.

**Comment by nolanzzz** [comment]
Issue solved
